/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package no.nav.nada;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class ComplexTypesOracleDatabaseDialectTest {
    @Test void testSomeLibraryMethod() {
        //ComplexTypesOracleDatabaseDialect classUnderTest = new ComplexTypesOracleDatabaseDialect();
        //assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }
}
